### ISSUE TITLE
URL of distribution changed

### ISSUE THREAD

**Issue by kronmar** [zazuko/ckan-datasets#5]
The `dcat:distribution` generates an URL based on the `schema:url` provided. During this step, the URL is slightly changed. In my use case, the URL
> https://int.lindas.admin.ch/sparql/#query=%23pragma+describe.strategy+cbd%0APREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%0ADESCRIBE+%3Fcube%0A%0AFROM+%3Chttps%3A%2F%2Flindas.admin.ch%2Ffoen%2Fcube%2Fwsl%3E%0AWHERE+%7B%0A++%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-90-None-None-24%2Fcube%3E+schema%3AhasPart+%3Fcube+.%0A++%3Fcube+schema%3Aversion+1+.%0A%7D%0A&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&requestMethod=POST&tabTitle=Totholzvolumen&headers=%7B%7D&outputFormat=rawResponse

is changed to
>https://int.lindas.admin.ch/sparql/#query=%23pragma+describe.strategy+cbd%0APREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%0ADESCRIBE+%3Fcube%0A%0AFROM+%3Chttps%3A%2F%2Flindas.admin.ch%2Ffoen%2Fcube%2Fwsl%3E%0AWHERE+%7B%0A++%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-90-None-None-24%2Fcube%3E+schema%3AhasPart+%3Fcube+.%0A++%3Fcube+schema%3Aversion+1+.%0A%7D%0A&amp;contentTypeConstruct=text%2Fturtle&amp;contentTypeSelect=application%2Fsparql-results%2Bjson&amp;endpoint=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&amp;requestMethod=POST&amp;tabTitle=Totholzvolumen&amp;headers=%7B%7D&amp;outputFormat=rawResponse

What happens, is that `&` are replaced by `&amp;`. This does not lead to an invalid URL in my case - although I can't be certain that this is always the case. However, the possibility to give the SPARQL Queries a proper name is lost here.  

<img width="849" alt="image" src="https://user-images.githubusercontent.com/95312586/186162452-af6acf74-cceb-497e-963d-9b19fe840216.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/95312586/186162604-309dd38f-6924-4bb0-8c4d-09488db96fa2.png">

**Comment by kronmar** [comment]
cc @pierredumas @Rdataflow

**Comment by tpluscode** [comment]
Where are these links being generated?

**Comment by Rdataflow** [comment]
@tpluscode effect is observable here
https://int.lindas.admin.ch/ckan?organization=https://register.ld.admin.ch/opendataswiss/org/bundesamt-fur-umwelt-bafu
search for `&amp;` 
encoding of `&amp;` probably happing somewhere within the functions called here https://github.com/zazuko/trifid-plugin-ckan/blob/364cbfecdda0b0d039cca4885e6fed5b91266f45/src/xml.js#L64

**Comment by Rdataflow** [comment]
origin of such data is i.e. here https://s.zazuko.com/WmMf3e
notice the unecoded `&`

**Comment by ludovicm67** [comment]
Hi @kronmar!

I took a quick look and I tried to open the two links (with and without encoded characters).
Both seems to open and generate a new tab with proper title.

I tried on Chrome and Firefox, latest versions.

Is it still something that requires some investigation, or is it working on your side also?

**Comment by kronmar** [comment]
Hi @ludovicm67 

That's a bit of an older topic... But yes, both links open now as expected, without a change of tab name. I tried in Microsoft Edge as well as Chrome. Seems to work properly now.

**Comment by ludovicm67** [comment]
Hi @kronmar!

Thank you for your feedback :)
